### ISSUE TITLE
Kwin6 support

### ISSUE THREAD

**Issue by dgudim** [Shaurya-Kalia/squash2#1]
Is this going to be ported to kwin6? 
Version from https://store.kde.org/p/1806319 (published 3 days ago) looks like a port but doesn't work (I think because of broken metadata)

**Comment by Shaurya-Kalia** [comment]
Yeah sorry for uploading work in progress. I was experimenting with curves a bit. In the end, went with the previous ones. Have uploaded the correct file now.
